from dataclasses import dataclass
from typing import Literal

@dataclass(slots=True)
class RunControlConfig:
    iteration_limit: int = ...
    log_level: Literal["DEBUG", "INFO", "RESULT", "WARNING", "ERROR", "CRITICAL"] = ...
    trace: bool = ...
    semi_eval_with_equality: bool = ...
    interactive_query_mode: Literal["interactive", "first", "all"] = ...
    save_solutions: bool = ...
    include_final_facts: bool = ...

@dataclass(slots=True)
class InferenceStrategyConfig:
    select_rules_num: int | Literal[-1] = ...
    select_facts_num: int | Literal[-1] = ...
    grounding_rule_strategy: Literal[
        "SequentialCyclic",
        "SequentialCyclicWithPriority",
        "SccSort",
        "ReverseSccSort",
    ] = ...
    grounding_term_strategy: Literal["Exhausted"] = ...
    question_rule_interval: int = ...
    stratified_negation_enabled: bool = ...
    stratified_negation_bailout_factor: int = ...

@dataclass(slots=True)
class GrounderConfig:
    grounding_rules_per_step: int | Literal[-1] = ...
    grounding_facts_per_rule: int | Literal[-1] = ...
    grounding_rules_num_every_step: int | Literal[-1] | None = ...
    grounding_facts_num_for_each_rule: int | Literal[-1] | None = ...
    allow_unify_with_nested_term: bool = ...
    conceptual_fuzzy_unification: bool = ...

@dataclass(slots=True)
class ExecutorConfig:
    executing_rule_num: int | Literal[-1] = ...
    executing_max_steps: int | Literal[-1] = ...
    anti_join_used_facts: bool = ...

@dataclass(slots=True)
class PathConfig:
    rule_dir: str = ...
    fact_dir: str = ...
    log_dir: str = ...

@dataclass(slots=True)
class KBConfig:
    fact_cache_size: int | Literal[-1] = ...

@dataclass(slots=True)
class Config:
    run: RunControlConfig
    strategy: InferenceStrategyConfig
    grounder: GrounderConfig
    executor: ExecutorConfig
    path: PathConfig
    engineering: KBConfig
    config: str | None
